#그룹 상태 

만들어진 그룹의 상태를 변경합니다. 변경된 항목에 대해 그룹 멤버에게 알림이 발송됩니다.

##API

```
PUT /groups/{groupId}
```

###Request###
{
    "status": "Closed"
}

####상태값####
Open : 모집중
Closed : 모집 완료
Inactive: 활동 중단
Delete: 삭제

###
1. 그룹장만 상태 변경 가능
2. Closed 상태에서는 그룹 가입 및 활동 불가
3. Delete 상태는 그룹 복구 불가