server:
  port: 8080

spring:
  application:
    name: sight-spring-backend
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    com.sight: INFO
    org.springframework: INFO

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sight}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      
logging:
  level:
    com.sight: DEBUG

auth:
  service:
    endpoint: ${AUTH_SERVICE_ENDPOINT:}
    api-key: ${AUTH_SERVICE_API_KEY:}

discord:
  token: ${DISCORD_BOT_TOKEN:}
  guild-id: ${DISCORD_GUILD_ID:}
  oauth2:
    client-id: ${DISCORD_OAUTH2_CLIENT_ID:}
    client-secret: ${DISCORD_OAUTH2_CLIENT_SECRET:}
    redirect-uri: ${DISCORD_OAUTH2_REDIRECT_URI:}
    state-secret: ${DISCORD_OAUTH2_STATE_SECRET:}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sight}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO

auth:
  service:
    endpoint: ${AUTH_SERVICE_ENDPOINT:}
    api-key: ${AUTH_SERVICE_API_KEY:}

discord:
  token: ${DISCORD_BOT_TOKEN:}
  guild-id: ${DISCORD_GUILD_ID:}
  oauth2:
    client-id: ${DISCORD_OAUTH2_CLIENT_ID:}
    client-secret: ${DISCORD_OAUTH2_CLIENT_SECRET:}
    redirect-uri: ${DISCORD_OAUTH2_REDIRECT_URI:}
    state-secret: ${DISCORD_OAUTH2_STATE_SECRET:}
